-- 테이블 삭제 (초기화용)
DROP TABLE SECURITY_AUTH CASCADE CONSTRAINTS;
DROP TABLE AUDIT_LOG CASCADE CONSTRAINTS;
DROP TABLE TRANSFER_DETAIL CASCADE CONSTRAINTS;
DROP TABLE TRANSACTION_HISTORY CASCADE CONSTRAINTS;
DROP TABLE TRANSACTION_STATUS CASCADE CONSTRAINTS;
DROP TABLE ACCOUNT CASCADE CONSTRAINTS;
DROP TABLE BANK CASCADE CONSTRAINTS;
DROP TABLE USERS CASCADE CONSTRAINTS;

-- 시퀀스 생성
CREATE SEQUENCE SEQ_USER_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_BANK_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_ACC_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_TRANS_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_STATUS_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DETAIL_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_LOG_ID START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_AUTH_ID START WITH 1 INCREMENT BY 1;

-- 1. 회원 테이블
CREATE TABLE USERS (
    USER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(30) NOT NULL,
    PWD_HASH VARCHAR2(100) NOT NULL,
    ROLE VARCHAR2(30) DEFAULT 'USER', -- ADMIN, USER
    IS_DELETED CHAR(1) DEFAULT 'N',
    CREATED_AT DATE DEFAULT SYSDATE
);

-- 2. 은행 테이블
CREATE TABLE BANK (
    BANK_ID NUMBER PRIMARY KEY,
    BANK_NAME VARCHAR2(30) NOT NULL,
    BANK_CODE VARCHAR2(30) NOT NULL
);

-- 3. 계좌 테이블
CREATE TABLE ACCOUNT (
    ACC_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(USER_ID),
    BANK_ID NUMBER REFERENCES BANK(BANK_ID),
    ACC_NUM VARCHAR2(30) UNIQUE NOT NULL,
    BALANCE NUMBER DEFAULT 0,
    ALIAS VARCHAR2(30)
);

-- 4. 거래상태 테이블
CREATE TABLE TRANSACTION_STATUS (
    STATUS_ID NUMBER PRIMARY KEY,
    STATUS_NAME VARCHAR2(30) NOT NULL
);

-- 5. 거래내역 테이블
CREATE TABLE TRANSACTION_HISTORY (
    TRANS_ID NUMBER PRIMARY KEY,
    ACC_ID NUMBER REFERENCES ACCOUNT(ACC_ID),
    STATUS_ID NUMBER REFERENCES TRANSACTION_STATUS(STATUS_ID),
    TRANS_TYPE VARCHAR2(30), -- 입금, 출금, 이체
    AMOUNT NUMBER NOT NULL,
    AFTER_BALANCE NUMBER,
    MEMO VARCHAR2(100),
    TRANS_DATE DATE DEFAULT SYSDATE
);

-- 6. 이체상세 테이블
CREATE TABLE TRANSFER_DETAIL (
    TRANSFER_ID NUMBER PRIMARY KEY,
    TRANS_ID NUMBER REFERENCES TRANSACTION_HISTORY(TRANS_ID),
    RECV_ACC_NUM VARCHAR2(30),
    RECV_MEMO VARCHAR2(100)
);

-- 7. 감사로그 테이블
CREATE TABLE AUDIT_LOG (
    LOG_ID NUMBER PRIMARY KEY,
    USER_ID NUMBER REFERENCES USERS(USER_ID),
    TRANS_ID NUMBER REFERENCES TRANSACTION_HISTORY(TRANS_ID),
    ACTION VARCHAR2(100),
    IP_ADDR VARCHAR2(45),
    LOG_DATE DATE DEFAULT SYSDATE
);

-- 8. 보안인증 테이블
CREATE TABLE SECURITY_AUTH (
    AUTH_ID NUMBER PRIMARY KEY,
    TRANS_ID NUMBER REFERENCES TRANSACTION_HISTORY(TRANS_ID),
    USER_ID NUMBER REFERENCES USERS(USER_ID),
    AUTH_CODE VARCHAR2(6),
    ATTEMPTS NUMBER(1) DEFAULT 0,
    METHOD VARCHAR2(20),
    EXPIRE_AT DATE,
    STATUS VARCHAR2(30) -- PENDING, VERIFIED, EXPIRED, BLOCKED
);

-- 초기 데이터 삽입
INSERT INTO BANK VALUES (SEQ_BANK_ID.NEXTVAL, '하나', '081');
INSERT INTO BANK VALUES (SEQ_BANK_ID.NEXTVAL, '우리', '020');
INSERT INTO BANK VALUES (SEQ_BANK_ID.NEXTVAL, '국민', '004');
INSERT INTO BANK VALUES (SEQ_BANK_ID.NEXTVAL, '신한', '088');
INSERT INTO BANK VALUES (SEQ_BANK_ID.NEXTVAL, '기업', '003');

INSERT INTO TRANSACTION_STATUS VALUES (1, '완료');
INSERT INTO TRANSACTION_STATUS VALUES (2, '실패');
INSERT INTO TRANSACTION_STATUS VALUES (3, '인증대기');
INSERT INTO TRANSACTION_STATUS VALUES (4, '지연대기');
INSERT INTO TRANSACTION_STATUS VALUES (5, '차단');

COMMIT;